---
application:
  name: "wechat-go"
  project: "zhu"
  organization: "QoveryCommunity"
databases:
- type: "MYSQL"
  name: "wechat-mysql"
  version: "6"
- type: "REDIS"
  name: "wechat-redis"
  version: "6"
routers:
- name: "main-wechat-go"
  routes:
  - application_name: "wechat-go"
    paths:
    - "/*"
