---
application:
  name: "wechat-go"
  project: "mywechat"
  organization: "QoveryCommunity"
  storage:
  - name: "data"
    size: "10"
    type: "ssd"
    mount_point: "/mnt/data"
databases:
- type: "MYSQL"
  name: "wechat-mysql"
  version: "8.0"
- type: "REDIS"
  name: "wechat-redis"
  version: "8.0"
routers:
- name: "main-wechat-go"
  routes:
  - application_name: "wechat-go"
    paths:
    - "/*"
